---
title: "Preliminary results of Pr(dead | forest structure, elevation) for #mtnclim2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r pressure, echo=FALSE}
# General and basic summary statistics for project

library(sf)
library(tidyverse)
library(purrr)
library(lme4)
library(effects)

all_sites <- list.files("data/data_output/classified/model-classified/augmented-crowns", full.names = TRUE)
all_site_names <- substr(list.files("data/data_output/classified/model-classified/augmented-crowns"), start = 1, stop = 9)

augmented_crowns <- 
  lapply(all_sites, FUN = readRDS) %>% 
  setNames(all_site_names)

all_site_bounds <-
  all_site_names %>% 
  map2(.y = augmented_crowns, .f = function(site, forest) {
    site_bounds <-
      sf::st_read(paste0("data/data_output/site_data/", site, "/", site, "_mission-footprint/", site, "_site-bounds.geoJSON")) %>% 
      sf::st_transform(st_crs(forest)) %>% 
      sf::st_geometry()
  }) %>% 
  setNames(all_site_names)

all_site_areas <-
  all_site_bounds %>% 
  map2_df(.y = all_site_names, .f = function(site_bounds, site_name) {
    data.frame(site = site_name, site_area = as.numeric(st_area(site_bounds)), stringsAsFactors = FALSE)
  })

# pull out just the data (ignoring all spatial components) in order to model the probability of a tree being alive
# given its spectral data
hcc_data <- lapply(augmented_crowns, FUN = as.data.frame) %>%
  do.call(rbind, .)

head(hcc_data)

hcc_data <- 
  hcc_data %>% 
  mutate(live = ifelse(live_prob > 0.5, yes = 1, no = 0))

summarized_hcc_data <-
  hcc_data %>% 
  group_by(forest, elev, rep, site, live) %>% 
  summarize(count = n()) %>% 
  spread(key = live, value = count) %>% 
  rename(dead = `0`, live = `1`) %>% 
  mutate(total_trees = dead + live) %>% 
  mutate(survivorship = live / total_trees) %>% 
  mutate(mortality = dead / total_trees) %>% 
  left_join(all_site_areas, by = "site") %>% 
  mutate(density = total_trees / (site_area / 10000))

write_csv(summarized_hcc_data, path = "data/data_output/summarized-non-spatial-site-data.csv")

ggplot(summarized_hcc_data, aes(x = density, y = mortality)) + 
  geom_point() +
  geom_smooth(method = "lm")

summarized_hcc_data %>% 
  arrange(mortality)
as.data.frame(summarized_hcc_data %>% arrange(mortality))
sum(summarized_hcc_data$total_trees)
sum(summarized_hcc_data$dead)
sum(summarized_hcc_data$dead) / sum(summarized_hcc_data$total_trees)


m1 <- glm(as.matrix(summarized_hcc_data[, c("live", "dead")]) ~ forest + elev + density, data = summarized_hcc_data, family = "binomial")
summary(m1)
hist(hcc_data$voronoi_area, breaks = 1000)
quantile(hcc_data$voronoi_area, probs = 0.5, na.rm = TRUE)
mean(hcc_data$voronoi_area, na.rm = TRUE)

s <- 
  hcc_data %>%
  dplyr::select(-voronoi_poly, -crown_poly) %>% 
  mutate(voronoi_area = as.numeric(voronoi_area)) %>% 
  filter(voronoi_area < 500) %>% 
  mutate_at(vars(elev, height, voronoi_area), funs(scale))

s$elev_relative <- factor(s$elev_relative, levels = c("lo", "mi", "hi"))
s$forest <- factor(s$forest, levels = c("sequ", "sier", "stan", "eldo"))

m2 <- glmer(live ~ voronoi_area*height + elev_relative + (1 | site), data = s[s$forest != "sier", ], family = "binomial", glmerControl(optimizer = "bobyqa"))
summary(m2)
e1 <- Effect(focal.predictors = c("voronoi_area", "height"), mod = m2, xlevels = list(voronoi_area = seq(-2, 2, length.out = 15), height = seq(-2, 2, length.out = 3)))

e1_gg <- as.data.frame(e1)
e1_gg

height_area_gg <- 
  ggplot(e1_gg, aes(x = rev(voronoi_area), y = plogis(fit), fill = as.factor(height))) +
  geom_ribbon(aes(ymin = plogis(lower), ymax = plogis(upper)), alpha = 0.4) +
  geom_line(lwd = 1) +
  scale_fill_viridis_d(name = "Tree\nheight\n(stdev)") +
  theme_bw() +
  xlab("Local density (standard deviations)") +
  ylab("Pr (live)") +
  theme(axis.title.y = element_text(angle = 0, vjust = 0.5, margin = margin(0, 18, 0, 0)),
        axis.title.x = element_text(margin = margin(18, 0, 0, 0)),
        axis.text = element_text(size = 32),
        axis.title = element_text(size = 32),
        legend.text = element_text(size = 32, hjust = 1),
        legend.title = element_text(size = 32, hjust = 0.5),
        legend.key.height = unit(0.05, "npc"),
        panel.grid = element_blank(),
        plot.margin = margin(50, 50, 50, 50, "points"))

ggsave(plot = height_area_gg, filename = "figures/height-area-model.png", height = 10, width = 12, units = "in", dpi = 600)

e2 <- Effect(focal.predictors = "elev_relative", mod = m2)

e2_gg <- as.data.frame(e2) 
e2_gg 

elev_gg <- 
  ggplot(e2_gg, aes(x = 1:3, y = plogis(fit))) +
  geom_line(lwd = 1) +
  geom_ribbon(aes(ymin = plogis(lower), ymax = plogis(upper)), alpha = 0.4) +
  theme_bw() +
  xlab("Elevation") +
  ylab("Pr (live)") +
  theme(axis.title.y = element_text(angle = 0, vjust = 0.5, margin = margin(0, 18, 0, 0)),
        axis.title.x = element_text(margin = margin(18, 0, 0, 0)),
        axis.text = element_text(size = 32),
        axis.title = element_text(size = 32),
        legend.text = element_text(size = 32, hjust = 1),
        legend.title = element_text(size = 32, hjust = 0.5),
        legend.key.height = unit(0.05, "npc"),
        panel.grid = element_blank(),
        plot.margin = margin(50, 50, 50, 50, "points")
  ) +
  scale_x_continuous(breaks = 1:3, labels = c("low", "mid", "high"))

ggsave(plot = elev_gg, filename = "figures/elev-model.png", height = 10, width = 12, units = "in", dpi = 600) 

```
